# Project-wide Gradle settings.
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AGP Required Flags
android.nonTransitiveRClass=true
android.nonFinalResIds=true
org.gradle.configuration-cache=true

# Unify Android preferences path - USE ONLY ONE
systemProp.ANDROID_USER_HOME=C:\\Users\\ojeri\\.android
